### ISSUE TITLE
Many stored 'Query and Filter' returning errors

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair-lsst-web#24]
Typically the error is:

> 1054 (42S22): Unknown column 'objects.latestrmag' in 'field list'

For example: https://lasair-iris.roe.ac.uk/query/202/

![image](https://user-images.githubusercontent.com/3385557/168043992-18ce6262-a8c0-41a5-8d60-c6494fa6601f.png)

**Comment by RoyWilliams** [comment]
That query was copied from the old Lasair, which has a different schema. The attribute is now called 'rmag'. Correct schema document is here https://lasair-iris.roe.ac.uk/schema

**Comment by thespacedoctor** [comment]
Are these queries stored in the database? If so, can you point me to where and I will fix all those queries that are broken?

**Comment by RoyWilliams** [comment]
Dave -- All the queries should now run cleanly, can you check please?
Log in to lasair-iris, and go to https://lasair-iris.roe.ac.uk/querylist/my/, then click each and click the button "Run this query".

**Comment by thespacedoctor** [comment]
Super!!!
